# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: build2Jar

on:
  push:
    branches:
      - master
#    tags:
#      - '*'

jobs:
  build:
    name: gradle build2Jar
    runs-on: macos-12 # 14G memory

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      # Validate Gradle Wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Make gradlew executable  #更改脚本权限
        run: chmod +x ./gradlew

#      - name: Build with Gradle
#        run: ./gradlew build2Jar

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
#      - name: Publish to GitHub Packages
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: publish
#        env:
#          USERNAME: ${{ github.actor }}
#          TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
#          name: test
          path: ./.github/workflows/*
