# This is a basic workflow to help you get started with Actions

name: TagRelease

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      # Validate Gradle Wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Make gradlew executable  #更改脚本权限
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build2Jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugins
          path: ./plugins/

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ''
          draft: true
          prerelease: true
          files: ./plugins/*
